### ISSUE TITLE
Can't craft blue power recipes

### ISSUE THREAD

**Issue by Rhendak** [Xaethon/Genesis#13]
Tools of blue power are no longer craftable after update 1.0.6. Neither does NEI show the recipe for them anymore.

**Comment by Xaethon** [comment]
Looks like Qmunity have a fix but haven't pushed a new build yet. I will add it to the next update whenever it becomes available.
https://github.com/Qmunity/BluePower/issues/324

**Comment by Xaethon** [comment]
Fixed via minetweaker in 1.0.8
