### ISSUE TITLE
Client crash when placing Osmium tools into crafting grid

### ISSUE THREAD

**Issue by pushedx** [Xaethon/Genesis#14]
I was trying to repair my Osmium tools, but the client crashes each time I place the first tool in the crafting grid. It also crashes when used in the 3x3 crafting grids.

Log (3x3 Player crafting grid): https://gist.github.com/pushedx/1512e7af7ac943f48fa3
Log (3x3 Tinker's Crafting grid): https://gist.github.com/pushedx/9818588f9c60d693ca40

This is happening on the OTE Genesis server.

**Comment by Trcx528** [comment]
Looks like botania's timeless ivy recipe (where you combine a tool with timeless ivy and 3 of the repair material) is causing this.  Looking at mekanism's code it's not clear what's going wrong, but it might be easiest just to wait for the pack to upgrade to mek 8 as I doubt aidancbrady will be supporting mek 7 for much longer.

**Comment by Xaethon** [comment]
Should be fixed in Mekanism 8. Let me know if its not.
