### ISSUE TITLE
Femtocraft, Internal Server Error

### ISSUE THREAD

**Issue by helkarakse** [Xaethon/Genesis#16]
Internal server error occurs when crafting the micro cube on a tico crafting table

Pastebin: http://pastebin.com/PNHH8uTB

**Comment by helkarakse** [comment]
Also happens with a vanilla crafting table, and also duplicates the item by crafting it and leaving the materials in the crafting table.

**Comment by helkarakse** [comment]
No problems when automatically crafting via applied energistics.

**Comment by LyraelRayne** [comment]
When this happens on a server the micro cube is dropped on the ground and the items left on the crafting table.

When placing the microcube the player is disconnected from the server, the item is placed in the world and the microcube also remains in the player's inventory making this item self-duping.

**Comment by LyraelRayne** [comment]
Also twice when this has happened my research had been reset when I logged back in :'(

**Comment by Xaethon** [comment]
Should be fixed in update 1.1.0

**Comment by LyraelRayne** [comment]
I placed a micro cube in 1.1.0 of the pack and I still had this issue. Not sure about crafting as attempting to progress research to the stage where I can make one is a bit too frustrating with the research bug also going on.
