### ISSUE TITLE
Rocket fuel Galacticraft

### ISSUE THREAD

**Issue by Docxx** [Xaethon/Genesis#18]
No way to make Rocket fuel, no oil spawn in the world/s to make the rocket fuel. There is an alternative using fragmented carbon, the recipe has been fixed but to make the machines to turn fragmented carbon into fuel require meteoric iron which only spawns on other planets. 

Love Docxx :P

**Comment by falon1000** [comment]
this has already been adressed from my ticket about the same thing :P

**Comment by Xaethon** [comment]
Already fixed
