### ISSUE TITLE
Bug with the server Genesis

### ISSUE THREAD

**Issue by LordxTheron** [Xaethon/Genesis#19]
It seems that every time the disarm spell is used it crashes the person using it and or the person it hits if the person is a real player. every time i used it on somebody we both crashed.

**Comment by Xaethon** [comment]
https://github.com/Mithion/ArsMagica2/issues/1048

I've disabled disarm for now.

**Comment by LordxTheron** [comment]
Can I get my points reset as well so I don't have that disarm skill
