### ISSUE TITLE
Breaking Tesseract Crash

### ISSUE THREAD

**Issue by Bryceclark56** [Xaethon/Genesis#20]
While attempting to break a Tesseract, my whole client crashed.

Details: I used a Tinkers Construct Pickaxe and the Tesseract has a signalum lock.

Crash Log: http://pastebin.com/P8k88ckK

**Comment by helkarakse** [comment]
https://github.com/BevoTechPack/BevoTechPack/issues/819 is a similar issue, looks like it's not fixed yet.

**Comment by Xaethon** [comment]
Fixed in 1.2.4
