### ISSUE TITLE
Galacticraft inventory crash

### ISSUE THREAD

**Issue by Docxx** [Xaethon/Genesis#29]
the client crashes to desktop when clicking on the GC inventory tab, this is a known conflict with ExtraTic and its advised to either rollback to 3.0.10.301 http://ci.micdoodle8.com/job/Galacticraft-1.7/301/ or update to 3.0.11

I live on mars so I can't go outside until the fix lol

**Comment by Xaethon** [comment]
Fixed in 1.1.1
