### ISSUE TITLE
Galacticraft Sealable Blocks

### ISSUE THREAD

**Issue by Chaoticxzombi** [Xaethon/Genesis#30]
There is a almost no configured non opaque blocks that are recognized by the GC sealers. The config shows that only glass panes are available for the sealer to recognize. Making it super hard to make a cool dome shaped moon base that can be sealed. 

I have gone through the config and found were the ids can be placed
http://gyazo.com/5c3611d3b96f13a55a71c3a816141210

Their is also a forum post on OTE awhile ago that someone else has posted. Might be outdated
https://www.otegamers.com/threads/enabling-other-glass-types-to-seal-galacticraft-rooms.10172/

**Comment by helkarakse** [comment]
Added in 9c74f6a2c4506d23c9a356efa8a62b028aa8f064
