### ISSUE TITLE
Magical forest biomes changed to different biomes since 1.1.1

### ISSUE THREAD

**Issue by LyraelRayne** [Xaethon/Genesis#31]
I'm not exactly sure how to describe this but in the mining world on the OTE genesis server there was definitely a magical forest biome in a certain location and there definitely were magical forest biomes spreading from some pure nodes I'd placed around my base. Those all appear to have turned into "plains" biomes in the overworld base and some rwg biomes in the mining world.

**Comment by Zyphron** [comment]
It seems there is a Biome ID conflict between Thaumcraft and RWG on biome ID 203.

**Comment by Xaethon** [comment]
RWG biome IDs changed, will fix this in the next update.

**Comment by LyraelRayne** [comment]
I just checked in 1.1.2 and biome IDs 201-204 inclusive are still used by both RWG and Thaumcraft.

**Comment by Xaethon** [comment]
Fixed
