### ISSUE TITLE
Erebus dimension is blank

### ISSUE THREAD

**Issue by Zyphron** [Xaethon/Genesis#35]
I just tried going to Erebus for the first time.  The whole dimension was blank.  The portal spawns in mid air, and there is just endless bedrock as far as I can tell.  

I am assuming this is not normal?  I have not played with Erebus before.

**Comment by Xaethon** [comment]
The portal sometimes bugs out and spawns on top of the solid bedrock layer at the top (the Erebus has a bedrock ceiling like the nether). I think this is related to your over world position, so you may need to try making the portal at a lower elevation.

**Comment by Zyphron** [comment]
This seems to be the case.  Thank you for the help.
