### ISSUE TITLE
Spell Effect ID conflicts: Ars Magica 2

### ISSUE THREAD

**Issue by XanthusAnon** [Xaethon/Genesis#36]
First time I've posted one of these but I actually have a few.

Ars Magica self buffs appear to have a mismatch with other mods, I've seen this posted around several areas (https://github.com/Mithion/ArsMagica2/issues/1074 and https://github.com/Mithion/ArsMagica2/issues/1103) but it appears this issue prevails here in this modpack.

I've attempted to try some unused potion ID's (201-229) but it results in client crash even if both server and client side are adjusted to match the ID changes. Additionally changing to the suggested ID's from issue 1103 (posted above) it results in a whole different sort of effects, not the desired ones.

**Comment by XanthusAnon** [comment]
Additionally any other items that apply effects to do with Ars Magica 2 (such as the water guardian pants armor that gives fast swimming in water) often results in crashes or odd behaviour. Anyone that wears the water guardian armor instantly crashes upon touching water.

**Comment by Xaethon** [comment]
Fixed in 1.2.4, sorry it took so long
