### ISSUE TITLE
Ic2 uranium is not generated

### ISSUE THREAD

**Issue by Saeldur** [Xaethon/Genesis#39]
IC2 uranium is not generated by COFH (You forgot it) meaning it has to be laser drilled or gained from nether uranium in order to get Uranium-235 to run the IC2 nuclear reactor, might be worth adding so it will generate.

**Comment by Theinventor10** [comment]
I 2nd this issue as I also experience it is impossible to get this uranium. It has to be laser drilled or got from nether for me.

**Comment by Xaethon** [comment]
Fixed
