### ISSUE TITLE
Oxygen and Gas-burning Generator Bug

### ISSUE THREAD

**Issue by Theinventor10** [Xaethon/Genesis#40]
When gas-burning generator is placed on a pipe containing oxygen the entire server crashes. This has happened twice and both times manually removal of the generator was required. the following are list of server crashes that occurred when this bug occurred. It is not the type of the pipe that caused the server crash. Addition to that it is not the type of block placed onto the pipe. It is the fluid or gas the pipe contains. Normally you would expect the gas generator to not accept oxygen and instead not crash. Addition to that other fluids or gasses may also cause similar crashes but are unknown. This has been a issue for the server and for other players. Finally I would like to say this is not urgent but an important bug to be fixed that will save the server from crashes.

Mod of pipe:      Pipe containing:            type of crash:              item placed onto pipe:
Ender IO             oxygen                           server crash                 Gas-burning generator
mekanism            oxygen                           server crash                 Gas-burning generator
Ender Io               hydrogen                         non                             Gas-burning generator
mekanism             hydrogen                         non                              Gas-burning generator

**Comment by Xaethon** [comment]
Fixed
