### ISSUE TITLE
Electric Age Suggestions

### ISSUE THREAD

**Issue by accelleon** [Xaethon/Genesis#41]
A handful of suggestions for ELN to bring it up to par with other mods.
The water turbine in my opinion is extremely under-powered, it has a 30W output yet is more expensive than the 50v turbine which has a 300W output. I think the power output should be doubled via I:waterTurbinePowerFactor.
The conversion from ELN to RF is way too little. Currently you get only ~375 rf/t per 10 200V turbines.  I think the ratio should be tripled for ELN -> IC2 and ELN -> TE. This will produce ~100rf/t per turbine.
Currently the light bulbs die too fast to be useful for any form of permanent lighting, I would recommend setting the lifetime of the bulbs to something more reasonable like 72 for economic and 48 for incandescent. 
Also oredict tungsten.

**Comment by Xaethon** [comment]
Fixed
