### ISSUE TITLE
Compressed Cobbelstone smelt recipe

### ISSUE THREAD

**Issue by Arkentosh** [Xaethon/Genesis#42]
It seems compressed cobblestone (The tier 1, 9 cobblestone version) can be smelted, resulting in a null Extra Utilities item with a development name and no model, it can also be cut into a facade equally an untextured item. (I'm somewhat concerned said item might be able to crash people's games)

**Comment by helkarakse** [comment]
Temporarily fixed with 9a1c2e42e153ed42504e2ed982e1ad65a899a8de
