### ISSUE TITLE
Attempting to break tesseract with swapper tool causes crash to desktop

### ISSUE THREAD

**Issue by Halikar** [Xaethon/Genesis#46]
Issue reported in IRC, work-a-round advice works (use actual wrench), log was requested by trcx.

Pastbin of log is here:

http://pastebin.com/Ztw1SJYG

**Comment by Halikar** [comment]
Posted to wrong github. Whoops.

**Comment by Xaethon** [comment]
https://github.com/CoFH/Feedback/issues/376 Fixed already, but can not update to latest CoFH because it is incompatible with Bungee.
