### ISSUE TITLE
Minechem Chemical Decomposer Bug

### ISSUE THREAD

**Issue by Theinventor10** [Xaethon/Genesis#47]
Recently I have lost 9chemical decomposers do to a bug. A moderator claims that this issue is because of Forge which deleted the item. This issue occurred on the morning of 4/25/15 after a new server update. After updating my client to the new version and logging on a noticed that 4 chemical decomposers were missing. I tried to replace them and lost the other 5. leaving about a 50% chance of the chemical decomposer of disappearing when placed on thermal dynamics itemduct. I condsider this issue to be moderately urgent, because of the resources lost on each time the bug occurs.

**Comment by Xaethon** [comment]
Fixed
