### ISSUE TITLE
Lag on server

### ISSUE THREAD

**Issue by khumps** [Xaethon/Genesis#49]
I have hosted many mod packs on my server that are bigger then this one(Resonant Rise 3 with most of the optional mods) and have had very little lag but seem to be getting tons of server running behind messages in the console when I run this pack(as high as 82000 ms behind!) seems to happen a lot at world gen but it also happens spontaneously.
Server specs:
i7 3770k @ 3.5GHz
32GB DDR3 RAM(9GB dedicated to server)
max of 4 people on at once

**Comment by Xaethon** [comment]
9 GB to the server is way too much and can cause garbage collection pauses to be quite large and cause issues. Other than that I'd need a server console log or warmroast stack or anything to help troubleshoot the issue, it runs fine on OTEs servers (each have 4 or 5 gb of RAM allocated btw)

I know you asked a while back about disabling world gen, if you did something incorrectly in that it could cause some issues but I doubt that's the cause, will be able to tell from a server log though. Lag during world gen is to be expected (2 world gen mods) and it is highly recommended that you world border and pregen your world to prevent this and seed changes from updates.

**Comment by khumps** [comment]
I will try lowering the ram to 4-5 I was going to do the world gen untill I found an uninterupted vein of over a stack of no (no fortune) :P so I never ended up modding the world gen. that ore spreadsheet was really useful. right after I posted I did download a mod called chunkgen(aallows u to pregen the world around a specofic area) and that seems to have helped a bit. I thought that realistic alpha was causing it like you said so I tried default lv type and realistic alpha with same results. Hopefully the lower ram and pregen will help!

**Comment by khumps** [comment]
on phone so will post log tomorrow. There are long error strings in console on startup that might cause it. Do u want just startup log or a log over long period?

**Comment by Xaethon** [comment]
Log over any period when its lagging should be fine, there will be errors in startup in any pack, those often aren't related to in game issues

**Comment by khumps** [comment]
thing is the lag is server cant keep up lag so console shows nothing and server times out
