### ISSUE TITLE
Sudden Major Lagspikes

### ISSUE THREAD

**Issue by apsand6** [Xaethon/Genesis#6]
There are sudden major lag spikes that explode in your face when you do things. i have only had two so far.

**Comment by Ryathael** [comment]
Do not know if this is the same problem or not, but I had a similar experience when mining a vein of Fire Infused Stone, my FPS dropped to 0-1, and never recovered.

**Comment by Xaethon** [comment]
Not enough info to even begin to guess as to what is happening or why it is. If you can provide more details, feel free to comment and I will take a look, but until then, closing.
